site_name: AWS Documentation
nav:
  - AWS: index.md
  - AWS Compute: ec2.md
  - AWS Load Balancers: elb.md
  - AWS Storage: storage.md
  - AWS EKS: eks.md
theme:
  name: material
  nav_style: dark
  palette:
    scheme: default
    primary: indigo
    accent: light blue
